### ISSUE TITLE
Can we get Input types as well?

### ISSUE THREAD

**Issue by insanebaba** [vikram25897/graphql_to_dart#1]
Is Input types in scope of this package? This package seems great to me as It provides all the minimal stuff(minus enums), But I'm reluctant to use it at the moment as it doesn't have enum support or input type support

**Comment by vikram25897** [comment]
@insanebaba I have been trying to get time to implement enum support but input-type also seems like a good addition. I'll work in it as well.

**Comment by Zony-Zhao** [comment]
Any progress on it? Really need it. This lib is the only one works for me. Artemis seems not easy to work with.
